# These are supported funding model platforms

github: [aireck2]
ko_fi: erickescriba # Replace with a single Ko-fi username
  - https://ko-fi.com/erickescriba
liberapay: erickescriba # Replace with a single Liberapay username
custom:
  - https://www.paypal.me/erickescriba
